import Image from "next/image";
export const metadata = {
    title: "BlackBird",
    description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
    return (
        <div className="w-full h-screen overflow-hidden flex">
            <div className="flex-1">
                <Image src={'/login.gif'} width={100} height={100} alt="this is an image" className="w-full h-full object-contain"></Image>
                {/* <video className="w-full h-full" src="/loginVdeo.mp4" autoPlay muted></video> */}
            </div>
            {children}
        </div>
    );
}
